
GET http://localhost:4000/api/calculate/fibonnaci?value=5

###

GET http://localhost:4000/api/calculate/checkPalindrome?string=5

###
GET http://localhost:4000/api/calculate/randomNumber?min=5&max=10

###
GET http://localhost:4000/api/calculate/reverseString?string=5
###
GET http://localhost:4000/api/calculate/sumOfDigits?number=5



// resource https://chat.openai.com/share/b6c693d9-f503-4377-aaf7-5f303a1c0357